from __future__ import annotations

__all__ = [
    "fn1_raw",
    "fn1_wrap",
    "fn1_wrap_0",
    "fn2_raw",
    "fn2_wrap",
    "fn2_wrap_0",
    "fn3_raw",
    "fn3_wrap",
    "fn3_wrap_0",
    "fn3_wrap_0_2",
    "fn3_wrap_2",
]

def fn1_raw(arg0: str) -> str: ...
def fn1_wrap(arg0: int | str) -> str: ...
def fn1_wrap_0(arg0: int | str) -> str: ...
def fn2_raw(arg0: int) -> int: ...
def fn2_wrap(arg0: int | str) -> int: ...
def fn2_wrap_0(arg0: int | str) -> int: ...
def fn3_raw(arg0: int, arg1: list[int], arg2: str) -> str: ...
def fn3_wrap(arg0: int | str, arg1: list[int], arg2: int | str) -> str: ...
def fn3_wrap_0(arg0: int | str, arg1: list[int], arg2: str) -> str: ...
def fn3_wrap_0_2(arg0: int | str, arg1: list[int], arg2: int | str) -> str: ...
def fn3_wrap_2(arg0: int, arg1: list[int], arg2: int | str) -> str: ...
