from __future__ import annotations

import typing

__all__ = ["fn_0_arg", "fn_0_or_1_arg", "fn_1_arg", "fn_1_or_2_or_3_arg", "fn_2_arg"]

def fn_0_arg(arg0: typing.Callable[[], int]) -> int: ...
@typing.overload
def fn_0_or_1_arg(arg0: typing.Callable[[], int]) -> int: ...
@typing.overload
def fn_0_or_1_arg(arg0: typing.Callable[[int], int]) -> int: ...
def fn_1_arg(arg0: typing.Callable[[int], int], arg1: int) -> int: ...
@typing.overload
def fn_1_or_2_or_3_arg(arg0: typing.Callable[[int], int]) -> int: ...
@typing.overload
def fn_1_or_2_or_3_arg(arg0: typing.Callable[[int, int], int]) -> int: ...
@typing.overload
def fn_1_or_2_or_3_arg(arg0: typing.Callable[[int, int, int], int]) -> int: ...
def fn_2_arg(arg0: typing.Callable[[int, int], int], arg1: int, arg2: int) -> int: ...
