from __future__ import annotations

__all__ = [
    "Base",
    "call_fn",
    "clear",
    "create",
    "create_and_store",
    "is_alive",
    "store",
]

class Base:
    def __init__(self, arg0: str) -> None: ...
    def fn(self) -> str: ...

def call_fn(arg0: str) -> str: ...
def clear() -> None: ...
def create(arg0: str) -> Base: ...
def create_and_store(arg0: str) -> Base: ...
def is_alive(arg0: str) -> bool: ...
def store(arg0: Base) -> None: ...
