#ifndef PROXYPYTHON_GLOBAL_H
#define PROXYPYTHON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROXYPYTHON_LIBRARY)
#  define PROXYPYTHONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROXYPYTHONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROXYPYTHON_GLOBAL_H
