name: Lint Plugin Python

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check format
        uses: ModOrganizer2/check-formatting-action@master
        with:
          check-path: "."
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v2
      - name: Check format Python tests
        run: |
          poetry install --no-root
          poetry run poe lint
