#ifndef PYTHONRUNNER_GLOBAL_H
#define PYTHONRUNNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PYTHONRUNNER_LIBRARY)
#  define PYTHONRUNNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PYTHONRUNNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PYTHONRUNNER_GLOBAL_H
